from .LGrad_trainer import LGradTrainer
from .LNP_trainer import LNPTrainer
from .GramNet_trainer import GramNetTrainer
from .FreDect_trainer import FreDectTrainer
from .CNNSpot_trainer import CNNSpotTrainer
from .UnivFD_trainer import UnivFDTrainer
from .NPR_trainer import NPRTrainer
from .SAFE_trainer import SAFETrainer
from .FatFormer_trainer import FatFormerTrainer
from .SimE_trainer import SimETrainer